#APP ENV
app:
  env: "dev" # dev,release
  sysname: "UserDemo"
  port: 8080
  domain: http://192.168.2.80:9534

#Mysql
mysql:
  dbname: "zta"
  prefix: "zta_"
  pool:
    pool-min-cap: 10
    pool-ex-cap: 5
    pool-max-cap: 40
    pool-idle-timeout: 3600
    pool-wait-count: 1000
    pool-wai-timeout: 30
#  write:
#    host: "127.0.0.1"
#    port: 23306
#    user: "root"
#    password: "123456"
  write:
    host: "192.168.2.80"
    port: 3306
    user: "root"
    password: "123456"
